version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .setup/php/Dockerfile
      args:
        user: ticto
        uid: 1000
    container_name: ticto_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ticto_network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: ticto_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ticto_network
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: ticto_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ticto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: ticto
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ticto_network

  redis:
    image: redis:7-alpine
    container_name: ticto_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ticto_network

volumes:
  mysql_data:
  redis_data:

networks:
  ticto_network:
    driver: bridge
